web/gisdrf/api/urls.py
# Django
from django.urls import path, include

# Routers
from rest_framework.routers import DefaultRouter

# API Viewsets
from .apiviews import (RestaurantListView,
    PersonListView)


app_name = "api"

# router = DefaultRouter()
# router.register('v1/restaurants', RestaurantListView, basename='restaurants')


urlpatterns = [
    path('v1/restaurants/', RestaurantListView.as_view(), name='restaurants_list'),
    path('v1/persons/', PersonListView.as_view(), name='persons_list'),
] 

# urlpatterns += router.urls

web/gisdrf/gisdrf/urls.py
# Django
from django.contrib.gis import admin
from django.urls import path, include
from django.conf import settings

# Language prefix
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [] 

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('restaurants.urls'), name="restaurants"),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        
    ] + urlpatterns

web/gisdrf/restaurants/urls.py
# Django
from django.urls import path

# Views
from .views import HomeView, get_csv_file, stream
from .views import StatusDetail, StatusList


app_name = "restaurants"


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('nearby/@<str:x>/<str:y>/', HomeView.as_view(), name='nearby'),
    path('nearby/csv_file/@<str:x>/<str:y>/', get_csv_file, name='csv_file'),

    path('stream/', stream, name='stream'),
    path('status-list/', StatusList.as_view(), name='status_list'),
    path('status-detail/<int:pk>', StatusDetail.as_view(), name='status_detail'),

] 

web/gisdrf/api/models.py
from django.db import models

# Create your models here.

web/gisdrf/locations/models.py
# Django
from django.contrib.gis.db import models

# Translation
from django.utils.translation import gettext as _


class Location(models.Model):
    """
        Clase abstracta de la cuál heredará todos los modelos que necesiten
        almacenar algún tipo de localización georeferencial.
    """
    address = models.CharField(_('Dirección'), max_length=100, null=True, blank=True)
    pnt = models.PointField(_('Punto de ubicación'), null=True, blank=True)

    modified_at = models.DateTimeField(_('Modificado'), auto_now=True)
    created_at = models.DateTimeField(_('Creado'), auto_now_add=True)

    class Meta:
        abstract=True

web/gisdrf/persons/models.py
# Django
from django.contrib.gis.db import models
from django.conf import settings

# Signals
from django.dispatch import receiver
from django.db.models.signals import pre_save

# Models
from locations.models import Location

# Utils
import geocoder


class Person(Location):
    """
    Heredamos de Location, el cuál tiene las siguientes propiedades:
        - address = models.CharField(max_length=100, null=True, blank=True)
        - pnt = models.PointField(null=True, blank=True)
        - modified_at = models.DateTimeField(auto_now=True)
        - created_at = models.DateTimeField(auto_now_add=True)
    """

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)



# Signals

@receiver(pre_save, sender=Person)
def getting_address(sender, instance, **kwargs):
    """
    Obtenemos la dirección del individuo a partir de sus cordenadas,
    con la ayuda de la API Geocoding de Google.
    """

    if instance.pnt:
        pnt_location = instance.pnt

        # Convertimos el objeto de localización a una string para consultar la API
        location_string = "%s %s" % (pnt_location.x, pnt_location.y)

        # Solicitamos INFO a la API de Google
        g = geocoder.google(location_string, method='reverse', key=settings.GOOGLE_API_KEY)

        address = g.json.get('address')
        instance.address = address

web/gisdrf/restaurants/models.py
# Django
from django.contrib.gis.db import models

# Models
from locations.models import Location

# Managers
from .managers import RestaurantManager

# Translation
from django.utils.translation import gettext_lazy as _


class Restaurant(Location):
    """
    Heredamos de Location, el cuál tiene las siguientes propiedades:
        - address = models.CharField(max_length=100, null=True, blank=True)
        - pnt = models.PointField(null=True, blank=True)
        - modified_at = models.DateTimeField(auto_now=True)
        - created_at = models.DateTimeField(auto_now_add=True)
    """

    name = models.CharField(_('Nombre del restaurante'), max_length=100)
    twenty_four_hours = models.BooleanField(_('¿Está abierto 24 horas?'), default=False)

    objects = RestaurantManager()

    class Meta:
        verbose_name = _('Restaurante')
        verbose_name_plural = _('Restaurantes')
        ordering = ['id']

    def __str__(self):
        return "{} - {}".format(self.name, self.address)

    def getting_location(self):
        pass

web/gisdrf/locations/views.py
from django.shortcuts import render

# Create your views here.

web/gisdrf/restaurants/views.py
# Django
from django.shortcuts import render, redirect
from django.views import View

# GeoDjango
from django.contrib.gis.geos import fromstr, Point
from django.contrib.gis.db.models.functions import Distance

# Models
from .models import Restaurant

# Utils
import django_excel as excel
from django.utils import timezone

# Tasks
from .tasks import show_hello_world
from .generate_csv import generate_csv


# Example view that will get real-time events on the client

from django.views import generic
from gisdrf.mixins import MercureMixin
from django.contrib.auth import get_user_model

# User Model
User = get_user_model()

class StatusList(MercureMixin, generic.ListView):
    template_name = "restaurants/sse.html"
    queryset = User.objects.all()

    mercure_subscribe_targets = ["test"]
    # mercure_publish_targets = ['status1']
    mercure_hub_topics = ["test"]
  
class StatusDetail(MercureMixin, generic.DetailView):
    template_name = "restaurants/sse.html"
    model = User


class HomeView(MercureMixin, View):
    template_name = "restaurants/index.html"

    def get(self, request, x=None, y=None, *args, **kwargs):
        """
        GET
        """
        show_hello_world.delay()
        
        context = {}

        if x and y:
            """
            Obtenemos los restaurantes más cercanos al usuario,
            a partir de las cordenadas obtenidas...
            """
            nearby_restaurants = Restaurant.objects.get_restaurants_near_pnt(x, y, results=20)
            context['restaurants'] = nearby_restaurants
            context['latitude'] = y
            context['longitude'] = x
        
        return render(request, self.template_name, context)


def get_csv_file(request, x, y):
    """
    Generamos el archivo CSV con los restaurantes ordenados
    según su distancia al usuario, y devolvemos el archivo CSV
    para su descarga...
    """

    export = generate_csv(x, y)

    # Creamos una string para nombrar al archivo a descargar.
    today = timezone.now()
    strToday = today.strftime("%Y/%m/%d-%H:%M:%S")
    file_name = "results-"+ strToday + ".csv"

    # Generamos el archivo CSV en memoria
    sheet = excel.pe.Sheet(export)

    return excel.make_response(sheet, "csv", file_name=file_name)



###
"""
LO SIGUIENTE TRATA DE UNA PRUEBA, NO FORMA PARTE
DE LA APLICACIÓN EN SI MISMA...
"""
import datetime
import time
from django.http import StreamingHttpResponse
def stream(request):
    """
    Implementación de SSE nativa con django.

    Leer más aqui:
    https://docs.djangoproject.com/en/3.0/ref/request-response/#django.http.StreamingHttpResponse
    """
    def event_stream():
        """
        Esto es un simple test para conocer el funcionamiento de 
        StreamingHttpResponse, básicamente, estará devolviendo al
        usuario una actualización de la hora correspondiente.

        Es necesario que el cliente se suscriba a este evento desde el template.

        EJ:

        <body>
            <h4>Getting server updates</h4>
            <div id="result"></div>
        </body>

        <script>
            if(typeof(EventSource) !== "undefined") {
            var source = new EventSource("{% url 'restaurants:stream' %}");
            source.onmessage = function(event) {
                console.log(event);
                document.getElementById("result").innerHTML += event.data + "<br>";
            };
            } else {
            document.getElementById("result").innerHTML = "Sorry, your browser does not support server-sent events...";
            }
        </script>
        """
        while True:
            time.sleep(3)
            yield 'data: The server time is: %s\n\n' % datetime.datetime.now()

    return StreamingHttpResponse(event_stream(), content_type='text/event-stream')

web/gisdrf/restaurants/templates/restaurants/index.html
{% extends 'base.html' %}
{% load restaurant_extras %}
{% url "restaurants:home" as nearby %}

{% block content %}
<div class="container mt-5">

    <div class="row mt-5">
        <div class="col-sm-12">
            <h1 class="text-center">Click to find the nearest restaurant</h1>
            <button id="find-me" class="btn btn-outline-danger btn-block btn-lg">Search!</button>

            {% if longitude and latitude %}
            <hr>

            <a class="btn btn-warning btn-block mt-3"
            href="{% url 'api:restaurants_list' %}?lat={{latitude}}&lng={{longitude}}"
            target="_blank">
            Results in API Endpoint</a>

            <a id="download-csv"
            class="btn btn-success btn-block mt-3"
            href="{% url "restaurants:csv_file" longitude latitude %}">
            Download Excel Results</a>

            {% endif %}

            <!-- <div class="mt-5">
                <h4>Getting server updates</h4>
                <p> { mercure_hub_url %} </p>
                <div id="result"></div>
            </div> -->

            <p id = "status"></p>
            <a id = "map-link" target="_blank"></a>
        </div>

        <div class="col-sm-12">
            {% if restaurants %}
            <div class="card">
                <ul class="list-group list-group-flush text-center">

                {% for restaurant in restaurants %}
                    <li class="list-group-item row">
                        <h4>{{ forloop.counter }}º</h4>

                        <div class="col">
                            <b>{{ restaurant.name | upper }}</b>
                        </div>

                        <div class="col">
                            <span>{{restaurant.distance | distance_format}}</span>
                        </div>
                    </li>
                {% empty %}
                    <li>Without results...</li>
                {% endfor %}

                </ul>
            </div>
            {% endif %}

        </div>
    </div>

</div>
{% endblock content %}

{% block scripts %}
    <!-- <script>
        if(typeof(EventSource) !== "undefined") {
        var source = new EventSource("{ mercure_hub_url %}");
        source.onmessage = function(event) {
            console.log(event);
            document.getElementById("result").innerHTML += event.data + "<br>";
        };
        } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support server-sent events...";
        }
    </script> -->

    <script>
        function geoFindMe() {
            const status = document.querySelector('#status');
            const mapLink = document.querySelector('#map-link');

            mapLink.href = '';
            mapLink.textContent = '';

        function success(position) {
            const latitude  = position.coords.latitude;
            const longitude = position.coords.longitude;

            status.textContent = '';
            mapLink.href = `https://www.openstreetmap.org/#map=18/${latitude}/${longitude}`;
            mapLink.className = `btn btn-outline-success btn-block`;
            mapLink.textContent = `Latitude: ${latitude} °, Longitude: ${longitude} °`;

            // var token = '{{ csrf_token }}';

            url = "/nearby/"
            var path = url + "@" + longitude + "/" + latitude;

            $.ajax({
                // headers: { 'X-CSRFToken': token },
                type: 'GET',
                // data: data,
                url: path,
                success: function(r) {
                    location.href = path;

                },
                error: function (a, b, c) {
                    console.log(a, b, c);
                }
            });

        }

        function error() {
            status.textContent = 'Unable to retrieve your location';
        }

        if (!navigator.geolocation) {
            status.textContent = 'Geolocation is not supported by your browser';
        } else {
            status.textContent = 'Locating…';
            navigator.geolocation.getCurrentPosition(success, error);
        }

        }

        document.querySelector('#find-me').addEventListener('click', geoFindMe);
    </script>
{% endblock scripts %}

web/gisdrf/restaurants/templates/restaurants/sse.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h1>SSE with Mercure Hub</h1>
                <h4>Getting server updates</h4>
                <span>{{ mercure_hub_url }}</span>
                <br><br>

                {% for user in user_list %}
                <div id="result">
                    User: {{ user.username }} <br> Status: {{ user.status }}
                </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}
    <script>
        if(typeof(EventSource) !== "undefined") {
        var source = new EventSource("{{ mercure_hub_url }}");
        source.onmessage = function(event) {
            console.log(event);
            document.getElementById("result").innerHTML += event.data + "<br>";
        };
        } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support server-sent events...";
        }
    </script>

{% endblock scripts %}

web/gisdrf/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    <title>Nearby Restaurants</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock content %}
    
    

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

web/gisdrf/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'restaurants:home' %}">Nearby Restaurants</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'restaurants:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          API
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'api:restaurants_list' %}" target="_blank">Restaurant List</a>
          {% if latitude and longitude %}
          <a class="dropdown-item" href="{% url 'api:restaurants_list' %}?lat={{latitude}}&lng={{longitude}}" target="_blank">Restaurant Near Me</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'api:restaurants_list' %}?lat=41.3880000&lng=2.1110000" target="_blank">Restaurant Near Me (Fake Location)</a>
        </div>
      </li>
    </ul>
  </div>
</nav>